version: "3.9"
services:
  web:
    image: neo-librus:latest
    command: gunicorn -k uvicorn.workers.UvicornWorker app.core.asgi:application -b 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=app.core.settings.production
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: librarius
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:7-alpine
