version: "3.9"
services:
  web:
    image: neo-librus:latest
    command: gunicorn -k uvicorn.workers.UvicornWorker app.core.asgi:application -b 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=app.core.settings.production
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: neo_librus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7-alpine
